# Generated by Django 4.1.4 on 2022-12-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listings_description_listings_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='type',
            field=models.CharField(choices=[('Record', 'Record'), ('Clothing', 'Clothing'), ('Poster', 'Posters'), ('Miscellaneous', 'Miscellaneous')], default='Record', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('HH', 'Hip Hop'), ('SP', 'Synth Pop'), ('AR', 'Alternative Rock')], max_length=5),
        ),
    ]
