# Generated by Django 4.1.4 on 2022-12-08 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listings_type_alter_band_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.band'),
        ),
    ]
